### ISSUE TITLE
Setup vercel

### ISSUE THREAD

**Issue by zakiego** [sainseni/what-i-read-today#6]

**Comment by zakiego** [comment]
Env kuhapus, mau setup vercel dan repo dibikin public @zekhoi

**Comment by zakiego** [comment]
Kayaknya perlu acc

<img width="912" alt="Screenshot 2023-02-01 at 20 32 36" src="https://user-images.githubusercontent.com/78015359/216043426-1d3a64d5-a30b-40b6-9926-a9d511525e13.png">

**Comment by zekhoi** [comment]
sudah acc
